Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,8 +47,8 @@ jobs:
           if [[ -n "$(git status --porcelain)" ]]; then
             echo "Local branch is not up to date with remote_branch. Committing and pushing latest code to Git"
             git commit -a -m "cicd update"
-            git pull --no-edit --no-rebase origin main
-            git push origin main || echo "Failed to push changes. Please check for conflicts."
+            git pull --no-edit --no-rebase origin cicd
+            git push origin cicd || echo "Failed to push changes. Please check for conflicts."
           else
             echo "Local branch is up to date with Remote branch. No changes to push."
             exit 0
